Rails.application.routes.draw do
  # get "/clothings", to: "clothings#index"
  post "/clothings", to: "clothings#create"
  delete "/clothings/:id", to: "clothings#delete"
  patch "/clothings/:id", to: "clothings#update"
  # get "/users", to: "users#index"
  get "/users/:username", to: "users#show"
  get "/outfits", to: "outfits#index"
  post "/outfits", to: "outfits#create"
  patch "/outfits/:id", to: "outfits#update"
  delete '/outfits/:id', to: "outfits#delete"
  get '/outfit_clothings', to: "outfit_clothings#index"
  post '/outfit_clothings', to: "outfit_clothings#create"
  delete '/outfit_clothings/:id', to: "outfit_clothings#delete"
end
